In [1]:
!pip install plotly

Requirement already satisfied: plotly in c:\users\boyko\appdata\local\programs\python\python311\lib\site-packages (6.6.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\boyko\appdata\local\programs\python\python311\lib\site-packages (from plotly) (2.18.1)
Requirement already satisfied: packaging in c:\users\boyko\appdata\roaming\python\python311\site-packages (from plotly) (26.0)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
%pip install nbformat

Requirement already satisfied: nbformat in c:\users\boyko\appdata\local\programs\python\python311\lib\site-packages (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\boyko\appdata\local\programs\python\python311\lib\site-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in c:\users\boyko\appdata\local\programs\python\python311\lib\site-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\boyko\appdata\roaming\python\python311\site-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in c:\users\boyko\appdata\roaming\python\python311\site-packages (from nbformat) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\boyko\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=2.6->nbformat) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\boyko\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\boyko\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\boyko\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\boyko\appdata\roaming\python\python311\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.6.0)
Requirement already satisfied: typing-extensions>=4.4.0 in c:\users\boyko\appdata\roaming\python\python311\site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [12]:
import pandas as pd

df = pd.read_csv('C:/Users/boyko/Downloads/dataset_crawler-google-places_2026-03-26_17-18-47-182 (1).csv') 
display(df.head())
columns_to_keep = ['title', 'street', 'reviewsCount', 'totalScore', 'text', 'publishedAtDate'] 

try:
    df_clean = df[columns_to_keep]
    # Nie potrzebujemy recenzji, w których ludzie po prostu wystawili gwiazdki, ale nic nie napisali
    df_clean = df_clean.dropna(subset=['text'])
    
    print(f"Gotowe! Pozostały jeszcze recenzje z tekstem do analizy: {len(df_clean)}")
except KeyError as e:
    print(f"Błąd: Nie mogę znaleźć takiej kolumny w pliku - {e}")
    print("Oto wszystkie kolumny zawarte w Twoim pliku:", df.columns.tolist())

,title,totalScore,reviewsCount,street,city,state,countryCode,website,phone,categories/0,categories/1,categories/2,categories/3,categories/4,categories/5,categories/6,url,categoryName
0,Żabka,4.6,139.0,Nałęczowska 30,Lublin,NaN,PL,https://www.zabka.pl/,+48 61 856 37 00,Sklep spożywczy,Sklep z piwem,Kawiarnia,Hot dogi,Kolportaż gazet,Sklep z winem,NaN,https://www.google.com/maps/search/?api=1&quer...,Sklep spożywczy
1,Żabka | Prosto z pieca,4.1,94.0,Pana Wołodyjowskiego 8,Lublin,NaN,PL,https://www.zabka.pl/,+48 61 856 37 00,Fast food,Sklep z piwem,Kawiarnia,Usługi kurierskie,Hot dogi,Kolportaż gazet,Sklep z winem,https://www.google.com/maps/search/?api=1&quer...,Fast food
2,Żabka,4.0,297.0,Szmaragdowa 24/6,Lublin,NaN,PL,https://www.zabka.pl/,+48 61 856 37 00,Fast food,Sklep z piwem,Kawiarnia,Usługi kurierskie,Hot dogi,Kolportaż gazet,Sklep z winem,https://www.google.com/maps/search/?api=1&quer...,Fast food
3,Żabka,4.2,195.0,Szafirowa 10,Lublin,NaN,PL,https://www.zabka.pl/,+48 61 856 37 00,Fast food,Sklep z piwem,Kawiarnia,Usługi kurierskie,Hot dogi,Kolportaż gazet,Sklep z winem,https://www.google.com/maps/search/?api=1&quer...,Fast food
4,Żabka,3.7,288.0,Nałęczowska 18/lok. 157,Lublin,NaN,PL,https://www.zabka.pl/,+48 61 856 37 00,Fast food,Sklep z piwem,Kawiarnia,Usługi kurierskie,Hot dogi,Kolportaż gazet,Sklep z winem,https://www.google.com/maps/search/?api=1&quer...,Fast food

Błąd: Nie mogę znaleźć takiej kolumny w pliku - "['text', 'publishedAtDate'] not in index"
Oto wszystkie kolumny zawarte w Twoim pliku: ['title', 'totalScore', 'reviewsCount', 'street', 'city', 'state', 'countryCode', 'website', 'phone', 'categories/0', 'categories/1', 'categories/2', 'categories/3', 'categories/4', 'categories/5', 'categories/6', 'url', 'categoryName']

In [13]:
import json
with open('C:/Users/boyko/Downloads/dataset_crawler-google-places_2026-03-26_17-18-47-182 (1).json', 'r', encoding='utf-8') as f:
    data = json.load(f)

print(f"Liczba sklepów w pliku: {len(data)}")

if len(data) > 0:

    # Wyświetlamy wszystkie klucze (nazwy kolumn/bloków) pierwszego elementu
    print(list(data[0].keys()))

Liczba sklepów w pliku: 3864
['title', 'reviewerId', 'reviewerUrl', 'name', 'reviewerNumberOfReviews', 'isLocalGuide', 'reviewerPhotoUrl', 'text', 'textTranslated', 'publishAt', 'publishedAtDate', 'likesCount', 'reviewId', 'reviewUrl', 'reviewOrigin', 'stars', 'rating', 'responseFromOwnerDate', 'responseFromOwnerText', 'reviewImageUrls', 'reviewContext', 'reviewDetailedRating', 'visitedIn', 'originalLanguage', 'translatedLanguage']

In [ ]:
import pandas as pd
import json
file_path = 'C:/Users/boyko/Downloads/dataset_crawler-google-places_2026-03-26_17-18-47-182 (1).json'

with open(file_path, 'r', encoding='utf-8') as f:
    data = json.load(f)
df = pd.DataFrame(data)

columns_to_keep = ['title', 'stars', 'text', 'textTranslated', 'publishedAtDate']

# Filtrujemy tabelę
df_clean = df[columns_to_keep].copy()

# usuwamy te recenzje, w których użytkownik po prostu przyznał gwiazdki, ale nic nie napisał
df_clean = df_clean.dropna(subset=['text'])

print(f"Opinie zawierające rzeczywisty tekst do analizy: {len(df_clean)}\n")
display(df_clean.head())

🔥 Готово! Відгуків із реальним текстом для аналізу: 1913

,title,stars,text,textTranslated,publishedAtDate
6,Żabka,4,Królowa sklepów osiedlowych współcześnie,NaN,2025-12-23T21:42:25.497Z
9,Żabka,1,"Wprowadzanie klienta w błąd, złe ceny przy pro...",NaN,2025-11-21T18:43:00.029Z
13,Żabka,5,12 pazdziernika obslugiwal mnie pan najmilsza...,NaN,2025-10-12T16:31:16.641Z
17,Żabka,5,"Fajnie mieć tą żabkę przy biurze. Czysto, hot ...",NaN,2025-09-14T14:24:27.608Z
21,Żabka,3,Jak każda Zabka. Drogo,NaN,2025-07-22T21:05:36.740Z

In [ ]:
#  Tworzymy kolumnę z tonacją opartą na gwiazdkach
def get_sentiment(stars):
    if stars <= 2:
        return 'Negative'
    elif stars == 3:
        return 'Neutral'
    else:
        return 'Positive'

df_clean['sentiment'] = df_clean['stars'].apply(get_sentiment)


df_clean['text_lower'] = df_clean['text'].str.lower()

def categorize_complaint(text):

    categories = {
        'Service & Queues (Obsługa i kolejki)': ['obsług', 'pan', 'pani', 'kasjer', 'kolejk', 'czeka', 'niemil', 'chamsk', 'woln'],
        'Food & Coffee (Jedzenie i kawa)': ['hot', 'dog', 'kaw', 'zimn', 'stare', 'nieswiez', 'jedzen', 'parówk'],
        'Prices & Scam (Ceny i oszustwa)': ['drog', 'cen', 'paragon', 'oszust', 'grosz', 'promocj', 'etykiet'],
        'Cleanliness (Czystość)': ['brud', 'śmierdz', 'zapach', 'bałagan'],
        'Working Hours/Closed (Godziny otwarcia/Dni zamknięcia)': ['zamknięt', 'otwart', 'godzin']
    }
    
    found_categories = []
    for category, keywords in categories.items():
        # Jeśli w recenzji znajduje się choćby jedno słowo z tej kategorii
        if any(keyword in text for keyword in keywords):
            found_categories.append(category)
            
    # Jeśli nic nie znaleźli
    if not found_categories:
        return 'Other (Інше)'
        
    # Jeśli opinia mieści się w kilku kategoriach, łączymy je
    return ' + '.join(found_categories)

#  Analizujemy WYŁĄCZNIE negatywne opinie
negative_reviews = df_clean[df_clean['sentiment'] == 'Negative'].copy()
negative_reviews['complaint_category'] = negative_reviews['text_lower'].apply(categorize_complaint)

print(" Number of negative reviews:", len(negative_reviews))
print("\n Top Reasons for Complaints in Żabki, Lublin:")
display(negative_reviews['complaint_category'].value_counts().head(10).to_frame(name='Liczba skarg'))

 Number of negative reviews: 698

 Top Reasons for Complaints in Żabki, Lublin:

                                                    Liczba skarg
complaint_category
Service & Queues (Obsługa i kolejki)                         252
Other (Інше)                                                 123
Service & Queues (Obsługa i kolejki) + Food & C...            78
Food & Coffee (Jedzenie i kawa)                               55
Service & Queues (Obsługa i kolejki) + Prices &...            47
Working Hours/Closed (Godziny otwarcia/Dni zamk...            41
Prices & Scam (Ceny i oszustwa)                               28
Service & Queues (Obsługa i kolejki) + Working ...            27
Service & Queues (Obsługa i kolejki) + Food & C...             9
Service & Queues (Obsługa i kolejki) + Cleanlin...             8

In [ ]:
import plotly.express as px

# (przedstawiamy 10 najczęstszych skarg)
top_complaints = negative_reviews['complaint_category'].value_counts().reset_index()
top_complaints.columns = ['Complaint category', 'Quantity']
top_complaints = top_complaints.head(10)


fig = px.bar(top_complaints, 
             x='Quantity', 
             y='Complaint category', 
             orientation='h',
             title=' Top 10 Reasons for Negative Reviews in Żabki (Lublin)',
             color='Quantity',
             color_continuous_scale='Reds', 
             text_auto=True)


fig.update_layout(yaxis={'categoryorder':'total ascending'}) 

fig.show()